steps:
  - id: install_packages
    name: gcr.io/cloud-builders/npm
    args: ['install', 'client/']

  - id: prerender_browser_files
    name: gcr.io/cloud-builders/yarn
    args: ['run-script build', 'client/']
    waitFor:
    - install_packages
  - id: copy_prerendered_files
    name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'client/build', 'server/static']
    waitFor:
    - prerender_browser_files

  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://$_BUCKET/app.yaml', 'server/app.yaml']
    waitFor:
    - copy_prerendered_files
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', --no-promote, 'server/']
