version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongo_connectoro
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'testserver'
      MONGO_INITDB_ROOT_PASSWORD: '1111'
      MONGO_INITDB_DATABASE: test1
    volumes:
      - ../mongodata:/var/lib/mongo_connectoro/data/db
    ports:
      - '27017:27017'
    networks:
      - common
    logging:
      driver: none
networks:
  common:

